apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: production-helm-guestbook
  name: production-helm-guestbook
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: helm-guestbook
    release: production-helm-guestbook
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-guestbook
    chart: helm-guestbook-0.1.0
    heritage: Helm
    release: production-helm-guestbook
  name: production-helm-guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook
      release: production-helm-guestbook
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: production-helm-guestbook
    spec:
      containers:
        - image: 382775818839.dkr.ecr.eu-central-1.amazonaws.com/gb-frontend:v5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: helm-guestbook
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 215m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
